### ISSUE TITLE
Deleted issue

### ISSUE THREAD

**Issue by Rustring** [fractureiser-investigation/fractureiser#127]
Deleted

**Comment by MohrJonas** [comment]
**Update: I was in the middle of writing this, when the issue was closed by the creator. I thought about deleting it, but maybe it might answer someone else's question.**

### Answering such a question with a clear yes or no is rather difficult, so let's look at what we know:
These are the default permissions for the PrismLauncher flakpak from flathub (https://flathub.org/apps/org.prismlauncher.PrismLauncher):
![image](https://github.com/trigram-mrp/fractureiser/assets/32023338/d4315849-4ce7-4723-8ecc-dea3a7a0b7be)
- As you can see, the sandbox has access to your hardware, so they could hypothetically speaking for example access your webcam and take pictures.
- They can also read the contents of your Downloads folder (`~/Downloads`)
- The next two permissions are for hugepages. I can't really say anything about that, maybe someone else here can shed some light on that.
- It can also read and write to the .ftba folder (`~/.ftba`) as well as create a folder in the discord flatpak.
- There is obviously also network access, so data exfiltration is possible.
- Regarding the legacy windowing system, X11 has never been great with security (keylogging, ...)

**_However, none of these this far strike me as super dangerous. Sure, somebody could probably exploit X11 and write a keylogger, but I guess the chances of this happening are really low._**

However, there are also other things to look at:
- A user could give the flatpak more permissions (using flatseal, for example). Something that comes to mind is a malicious mod that checks if it is run in flatpak, then displays a fake error message and tells the user that more permissions are needed (social engineering).
- There are also security concerns from the sandbox itself, which you can for example find here: https://flatkill.org/

**Comment by Rustring** [comment]
Thanks, I use Wayland bc X11 just breaks for some reason
Edit: Oh so Prism uses Xwayland that clears something
